name: ğŸš€ Deploy Fiori UI5 Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸŒ Setup Node.js Environment
        uses: actions/setup-node@v4.2.0

      - name: ğŸ“¦ Install WGET
        run: |
          sudo apt-get install -y wget

      - name: Install Cloud Foundry CLI
        run: |
          # Install Cloud Foundry CLI
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf8-cli
          cf install-plugin -f https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/download/multiapps-plugin.linux64

      - name: Install CAP dependencies
        run: |
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin multiapps -f
          cf install-plugin html5-plugin -f

      - name: ğŸ”„ Update Linux Dependencies
        run: |
          sudo apt-get update

      - name: ğŸ”‘ Log into BTP Cloud Foundry
        run: |
          cf login -a ${{ secrets.BTP_CLOUD_FOUNDRY_API }} -u ${{ secrets.BTP_CLOUD_FOUNDRY_USERNAME }} -p '${{ secrets.BTP_CLOUD_FOUNDRY_PASSWORD }}' -o ${{ secrets.BTP_CLOUD_FOUNDRY_ORGANIZATION }} -s ${{ secrets.BTP_CLOUD_FOUNDRY_SPACE }}

      - name: ğŸ“¦ Install Dependencies
        run: |
          npm install

      - name: ğŸ› ï¸ Build TypeScript
        run: |
          npm run build

      - name: ğŸ› ï¸ Build MTA
        run: |
          npm run build:mta

      - name: ğŸš€ Deploy Application
        run: |
          npm run deploy:cf

      - name: ğŸ”’ Logout from BTP Cloud Foundry
        run: |
          cf logout
